<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dhirendra349101" ignored="0" name="Test" tests="4" failures="1" timestamp="28 Jun 2018 14:09:06 GMT" time="82.923" errors="0">
  <testcase name="VerifyLogin" time="51.788" classname="Test.LoginTest"/>
  <testcase name="VeriyAddAddress" time="16.78" classname="Test.LoginTest">
    <failure type="java.lang.AssertionError" message="Passed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Passed expected [true] but found [false]
at Test.LoginTest.VeriyAddAddress(LoginTest.java:96)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- VeriyAddAddress -->
  <testcase name="Printtest" time="0.004" classname="Test.PrintingTestCase"/>
  <testcase name="VerifyCart" time="13.019" classname="Test.AddCartTest"/>
</testsuite> <!-- Test -->
