<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dhirendra349101" ignored="2" name="Test" tests="2" failures="1" timestamp="27 Jun 2018 15:55:46 GMT" time="0.272" errors="0">
  <testcase name="VeriyAddAddress" time="0.016" classname="Test.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Page.LoginPage.addAddress(LoginPage.java:60)
	at Test.LoginTest.VeriyAddAddress(LoginTest.java:87)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- VeriyAddAddress -->
  <testcase name="Printtest" time="0.001" classname="Test.PrintingTestCase"/>
  <testcase name="VerifyLogin" time="0.0" classname="Test.LoginTest">
    <ignored/>
  </testcase> <!-- VerifyLogin -->
  <testcase name="VerifyCart" time="0.0" classname="Test.AddCartTest">
    <ignored/>
  </testcase> <!-- VerifyCart -->
</testsuite> <!-- Test -->
